openapi: 3.0.0
paths:
  /:
    get:
      tags:
      - API Info
      summary: Get API info
      description: Return basic information about the API
      operationId: api.controllers.default_controller.default_info
      parameters:
      - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          description: API default information
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BasicInfo'
              example:
                title: Wazuh API
                api_version: v4.5.0
                revision: '40100'
                license_name: GPL 2.0
                license_url: https://github.com/wazuh/wazuh/blob/v4.9.1/LICENSE
                hostname: wazuh
                timestamp: '2019-04-02T08:08:11Z'
components:
  schemas:
    BasicInfo:
      type: object
      properties:
        title:
          type: string
          description: API title name
        api_version:
          type: string
          description: API version in the manager
        revision:
          type: integer
          description: API revision
          format: int32
        license_name:
          type: string
          description: API license name
        license_url:
          type: string
          description: API license url
        hostname:
          type: string
          description: Server hostname
        timestamp:
          type: string
  responses: {}
  parameters:
    pretty:
      in: query
      name: pretty
      description: Show results in human-readable format
      schema:
        type: boolean
        default: false
