openapi: 3.0.0
paths:
  /overview/agents:
    get:
      tags:
      - Overview
      summary: Get agents overview
      description: Return a dictionary with a full agents overview
      operationId: api.controllers.overview_controller.get_overview_agents
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/agent:read'
      - $ref: '#/x-rbac-catalog/actions/group:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      responses:
        '200':
          description: Overview of agents
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/OverviewAgents'
              example:
                data:
                  nodes:
                  - node_name: worker1
                    count: 1
                  - node_name: worker2
                    count: 1
                  - node_name: master-node
                    count: 1
                  groups:
                  - name: default
                    count: 6
                    mergedSum: 9a016508cea1e997ab8569f5cfab30f5
                    configSum: ab73af41699f13fdd81903b5f23d8d00
                  agent_os:
                  - os:
                      name: Ubuntu
                      platform: ubuntu
                      version: 20.04.02 LTS
                    count: 6
                  agent_status:
                    active: 6
                    disconected: 0
                    never_connected: 0
                    pending: 0
                    total: 6
                  agent_version:
                  - version: Wazuh v4.3.0
                    count: 6
                  last_registered_agent:
                  - os:
                      arch: x86_64
                      codename: Focal Fossa
                      major: '20'
                      minor: '04'
                      name: Ubuntu
                      platform: ubuntu
                      uname: Linux |77000bae7bd0 |5.8.0-45-generic |#51~20.04.1-Ubuntu
                        SMP Tue Feb 23 13:46:31 UTC 2021 |x86_64
                      version: 20.04.02 LTS
                    node_name: worker1
                    lastKeepAlive: '2021-05-31T10:56:52Z'
                    configSum: ab73af41699f13fdd81903b5f23d8d00
                    status: active
                    ip: 172.18.0.7
                    group:
                    - default
                    name: 77000bae7bd0
                    registerIP: any
                    dateAdd: '2021-05-31T09:49:28Z'
                    manager: wazuh-worker1
                    id: '004'
                    mergedSum: 9a016508cea1e997ab8569f5cfab30f5
                    version: Wazuh v4.3.0
                    status_code: 0
                    group_config_status: active
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        message:
          type: string
          description: Human readable description to explain the result of the request
    OverviewAgents:
      type: object
      required:
      - agent_os
      - agent_status
      - agent_version
      - groups
      - last_registered_agent
      - nodes
      properties:
        nodes:
          type: array
          description: Active nodes in the cluster
          items:
            type: object
            properties:
              count:
                type: integer
                format: int32
              node_name:
                type: string
                format: alphanumeric_symbols
        groups:
          type: array
          description: Recount of the number of Wazuh agents group by Wazuh groups
          items:
            $ref: '#/components/schemas/AgentGroup'
        agent_os:
          type: array
          description: Recount of the number of Wazuh agents group by OS
          items:
            type: object
            properties:
              count:
                type: integer
                format: int32
              os:
                type: object
                properties:
                  name:
                    type: string
                    format: alphanumeric_symbols
                  platform:
                    type: string
                    format: alphanumeric_symbols
                  version:
                    type: string
                    format: alphanumeric_symbols
        agent_status:
          $ref: '#/components/schemas/AgentsSummaryStatus'
        agent_version:
          type: array
          description: Recount of the number of Wazuh agents group by version
          items:
            type: object
            properties:
              count:
                type: integer
                format: int32
              version:
                type: string
                format: alphanumeric_symbols
        last_registered_agent:
          type: array
          items:
            $ref: '#/components/schemas/Agent'
  responses:
    ResponseError:
      description: Response to report a bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'
          example:
            title: Bad Request
            detail: '''{invalid_param}'' is not a ''{expected_type}''. Failed validating
              ''format'' in schema[''items'']: {''description'': ''{parameter_name}'',
              ''format'': ''{expected_format}'', ''minLength'': {expected_length},
              ''type'': ''{expected_type}'', ''x-scope'': ['''', ''#/components/parameters/{parameter_name}'']}'
    PermissionDeniedResponse:
      description: Response to report a permission denied request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          example:
            title: Permission Denied
            detail: 'Permission denied: Resource type: *:*'
            remediation: Please, make sure you have permissions to execute the current
              request. For more information on how to set up permissions, please visit
              https://documentation.wazuh.com/4.9/user-manual/api/rbac/configuration.html
            error: 4000
            dapi_errors:
              unknown-node:
                error: 'Permission denied: Resource type: *:*'
    UnauthorizedResponse:
      description: Response to report an unauthorized request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'
          example:
            title: Unauthorized
            detail: No authorization token provided
    InvalidHTTPMethodResponse:
      description: Response to report an invalid HTTP method
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'
          example:
            title: Method Not Allowed
            detail: Specified method is invalid for this resource
    TooManyRequestsResponse:
      description: Maximum number of request per minute reached
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'
          example:
            title: Wazuh Error
            detail: Maximum number of requests per minute reached
            remediation: 'This limit can be changed in api.yaml file. More information
              here: https://documentation.wazuh.com/4.9/user-manual/api/security/configuration.html'
            code: 6001
  parameters:
    pretty:
      in: query
      name: pretty
      description: Show results in human-readable format
      schema:
        type: boolean
        default: false
    wait_for_complete:
      in: query
      name: wait_for_complete
      description: Disable timeout response
      schema:
        type: boolean
        default: false
